// http://utf-8.jp/public/aaencode.html
// Wrapper generated by the program.
module.exports = {
  $sig: {
    name: 'wrapper',
    partialArray: [
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "Identifier",
            "name": "ﾟωﾟﾉ"
          },
          "right": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "Literal",
              "value": {},
              "regex": {
                "pattern": "｀ｍ´）ﾉ ~┻━┻   ",
                "flags": ""
              }
            },
            "property": {
              "type": "Literal",
              "value": "_"
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "Identifier",
            "name": "o"
          },
          "right": {
            "type": "AssignmentExpression",
            "operator": "=",
            "left": {
              "type": "Identifier",
              "name": "ﾟｰﾟ"
            },
            "right": {
              "type": "AssignmentExpression",
              "operator": "=",
              "left": {
                "type": "Identifier",
                "name": "_"
              },
              "right": {
                "type": "Literal",
                "value": 3
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "Identifier",
            "name": "c"
          },
          "right": {
            "type": "AssignmentExpression",
            "operator": "=",
            "left": {
              "type": "Identifier",
              "name": "ﾟΘﾟ"
            },
            "right": {
              "type": "BinaryExpression",
              "operator": "-",
              "left": {
                "type": "Identifier",
                "name": "ﾟｰﾟ"
              },
              "right": {
                "type": "Identifier",
                "name": "ﾟｰﾟ"
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "Identifier",
            "name": "ﾟДﾟ"
          },
          "right": {
            "type": "AssignmentExpression",
            "operator": "=",
            "left": {
              "type": "Identifier",
              "name": "ﾟΘﾟ"
            },
            "right": {
              "type": "BinaryExpression",
              "operator": "/",
              "left": {
                "type": "BinaryExpression",
                "operator": "^",
                "left": {
                  "type": "BinaryExpression",
                  "operator": "^",
                  "left": {
                    "type": "Identifier",
                    "name": "o"
                  },
                  "right": {
                    "type": "Identifier",
                    "name": "_"
                  }
                },
                "right": {
                  "type": "Identifier",
                  "name": "o"
                }
              },
              "right": {
                "type": "BinaryExpression",
                "operator": "^",
                "left": {
                  "type": "BinaryExpression",
                  "operator": "^",
                  "left": {
                    "type": "Identifier",
                    "name": "o"
                  },
                  "right": {
                    "type": "Identifier",
                    "name": "_"
                  }
                },
                "right": {
                  "type": "Identifier",
                  "name": "o"
                }
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "Identifier",
            "name": "ﾟДﾟ"
          },
          "right": {
            "type": "ObjectExpression",
            "properties": [
              {
                "type": "Property",
                "key": {
                  "type": "Identifier",
                  "name": "ﾟΘﾟ"
                },
                "computed": false,
                "value": {
                  "type": "Literal",
                  "value": "_"
                },
                "kind": "init",
                "method": false,
                "shorthand": false
              },
              {
                "type": "Property",
                "key": {
                  "type": "Identifier",
                  "name": "ﾟωﾟﾉ"
                },
                "computed": false,
                "value": {
                  "type": "MemberExpression",
                  "computed": true,
                  "object": {
                    "type": "BinaryExpression",
                    "operator": "+",
                    "left": {
                      "type": "BinaryExpression",
                      "operator": "==",
                      "left": {
                        "type": "Identifier",
                        "name": "ﾟωﾟﾉ"
                      },
                      "right": {
                        "type": "Literal",
                        "value": 3
                      }
                    },
                    "right": {
                      "type": "Literal",
                      "value": "_"
                    }
                  },
                  "property": {
                    "type": "Identifier",
                    "name": "ﾟΘﾟ"
                  }
                },
                "kind": "init",
                "method": false,
                "shorthand": false
              },
              {
                "type": "Property",
                "key": {
                  "type": "Identifier",
                  "name": "ﾟｰﾟﾉ"
                },
                "computed": false,
                "value": {
                  "type": "MemberExpression",
                  "computed": true,
                  "object": {
                    "type": "BinaryExpression",
                    "operator": "+",
                    "left": {
                      "type": "Identifier",
                      "name": "ﾟωﾟﾉ"
                    },
                    "right": {
                      "type": "Literal",
                      "value": "_"
                    }
                  },
                  "property": {
                    "type": "BinaryExpression",
                    "operator": "^",
                    "left": {
                      "type": "BinaryExpression",
                      "operator": "^",
                      "left": {
                        "type": "Identifier",
                        "name": "o"
                      },
                      "right": {
                        "type": "Identifier",
                        "name": "_"
                      }
                    },
                    "right": {
                      "type": "BinaryExpression",
                      "operator": "-",
                      "left": {
                        "type": "Identifier",
                        "name": "o"
                      },
                      "right": {
                        "type": "Identifier",
                        "name": "ﾟΘﾟ"
                      }
                    }
                  }
                },
                "kind": "init",
                "method": false,
                "shorthand": false
              },
              {
                "type": "Property",
                "key": {
                  "type": "Identifier",
                  "name": "ﾟДﾟﾉ"
                },
                "computed": false,
                "value": {
                  "type": "MemberExpression",
                  "computed": true,
                  "object": {
                    "type": "BinaryExpression",
                    "operator": "+",
                    "left": {
                      "type": "BinaryExpression",
                      "operator": "==",
                      "left": {
                        "type": "Identifier",
                        "name": "ﾟｰﾟ"
                      },
                      "right": {
                        "type": "Literal",
                        "value": 3
                      }
                    },
                    "right": {
                      "type": "Literal",
                      "value": "_"
                    }
                  },
                  "property": {
                    "type": "Identifier",
                    "name": "ﾟｰﾟ"
                  }
                },
                "kind": "init",
                "method": false,
                "shorthand": false
              }
            ]
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "Identifier",
              "name": "ﾟДﾟ"
            },
            "property": {
              "type": "Identifier",
              "name": "ﾟΘﾟ"
            }
          },
          "right": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "BinaryExpression",
              "operator": "+",
              "left": {
                "type": "BinaryExpression",
                "operator": "==",
                "left": {
                  "type": "Identifier",
                  "name": "ﾟωﾟﾉ"
                },
                "right": {
                  "type": "Literal",
                  "value": 3
                }
              },
              "right": {
                "type": "Literal",
                "value": "_"
              }
            },
            "property": {
              "type": "BinaryExpression",
              "operator": "^",
              "left": {
                "type": "BinaryExpression",
                "operator": "^",
                "left": {
                  "type": "Identifier",
                  "name": "c"
                },
                "right": {
                  "type": "Identifier",
                  "name": "_"
                }
              },
              "right": {
                "type": "Identifier",
                "name": "o"
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "Identifier",
              "name": "ﾟДﾟ"
            },
            "property": {
              "type": "Literal",
              "value": "c"
            }
          },
          "right": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "BinaryExpression",
              "operator": "+",
              "left": {
                "type": "Identifier",
                "name": "ﾟДﾟ"
              },
              "right": {
                "type": "Literal",
                "value": "_"
              }
            },
            "property": {
              "type": "BinaryExpression",
              "operator": "-",
              "left": {
                "type": "BinaryExpression",
                "operator": "+",
                "left": {
                  "type": "Identifier",
                  "name": "ﾟｰﾟ"
                },
                "right": {
                  "type": "Identifier",
                  "name": "ﾟｰﾟ"
                }
              },
              "right": {
                "type": "Identifier",
                "name": "ﾟΘﾟ"
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "Identifier",
              "name": "ﾟДﾟ"
            },
            "property": {
              "type": "Literal",
              "value": "o"
            }
          },
          "right": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "BinaryExpression",
              "operator": "+",
              "left": {
                "type": "Identifier",
                "name": "ﾟДﾟ"
              },
              "right": {
                "type": "Literal",
                "value": "_"
              }
            },
            "property": {
              "type": "Identifier",
              "name": "ﾟΘﾟ"
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "Identifier",
            "name": "ﾟoﾟ"
          },
          "right": {
            "type": "BinaryExpression",
            "operator": "+",
            "left": {
              "type": "BinaryExpression",
              "operator": "+",
              "left": {
                "type": "BinaryExpression",
                "operator": "+",
                "left": {
                  "type": "BinaryExpression",
                  "operator": "+",
                  "left": {
                    "type": "BinaryExpression",
                    "operator": "+",
                    "left": {
                      "type": "BinaryExpression",
                      "operator": "+",
                      "left": {
                        "type": "BinaryExpression",
                        "operator": "+",
                        "left": {
                          "type": "BinaryExpression",
                          "operator": "+",
                          "left": {
                            "type": "BinaryExpression",
                            "operator": "+",
                            "left": {
                              "type": "BinaryExpression",
                              "operator": "+",
                              "left": {
                                "type": "MemberExpression",
                                "computed": true,
                                "object": {
                                  "type": "Identifier",
                                  "name": "ﾟДﾟ"
                                },
                                "property": {
                                  "type": "Literal",
                                  "value": "c"
                                }
                              },
                              "right": {
                                "type": "MemberExpression",
                                "computed": true,
                                "object": {
                                  "type": "Identifier",
                                  "name": "ﾟДﾟ"
                                },
                                "property": {
                                  "type": "Literal",
                                  "value": "o"
                                }
                              }
                            },
                            "right": {
                              "type": "MemberExpression",
                              "computed": true,
                              "object": {
                                "type": "BinaryExpression",
                                "operator": "+",
                                "left": {
                                  "type": "Identifier",
                                  "name": "ﾟωﾟﾉ"
                                },
                                "right": {
                                  "type": "Literal",
                                  "value": "_"
                                }
                              },
                              "property": {
                                "type": "Identifier",
                                "name": "ﾟΘﾟ"
                              }
                            }
                          },
                          "right": {
                            "type": "MemberExpression",
                            "computed": true,
                            "object": {
                              "type": "BinaryExpression",
                              "operator": "+",
                              "left": {
                                "type": "BinaryExpression",
                                "operator": "==",
                                "left": {
                                  "type": "Identifier",
                                  "name": "ﾟωﾟﾉ"
                                },
                                "right": {
                                  "type": "Literal",
                                  "value": 3
                                }
                              },
                              "right": {
                                "type": "Literal",
                                "value": "_"
                              }
                            },
                            "property": {
                              "type": "Identifier",
                              "name": "ﾟｰﾟ"
                            }
                          }
                        },
                        "right": {
                          "type": "MemberExpression",
                          "computed": true,
                          "object": {
                            "type": "BinaryExpression",
                            "operator": "+",
                            "left": {
                              "type": "Identifier",
                              "name": "ﾟДﾟ"
                            },
                            "right": {
                              "type": "Literal",
                              "value": "_"
                            }
                          },
                          "property": {
                            "type": "BinaryExpression",
                            "operator": "+",
                            "left": {
                              "type": "Identifier",
                              "name": "ﾟｰﾟ"
                            },
                            "right": {
                              "type": "Identifier",
                              "name": "ﾟｰﾟ"
                            }
                          }
                        }
                      },
                      "right": {
                        "type": "MemberExpression",
                        "computed": true,
                        "object": {
                          "type": "BinaryExpression",
                          "operator": "+",
                          "left": {
                            "type": "BinaryExpression",
                            "operator": "==",
                            "left": {
                              "type": "Identifier",
                              "name": "ﾟｰﾟ"
                            },
                            "right": {
                              "type": "Literal",
                              "value": 3
                            }
                          },
                          "right": {
                            "type": "Literal",
                            "value": "_"
                          }
                        },
                        "property": {
                          "type": "Identifier",
                          "name": "ﾟΘﾟ"
                        }
                      }
                    },
                    "right": {
                      "type": "MemberExpression",
                      "computed": true,
                      "object": {
                        "type": "BinaryExpression",
                        "operator": "+",
                        "left": {
                          "type": "BinaryExpression",
                          "operator": "==",
                          "left": {
                            "type": "Identifier",
                            "name": "ﾟｰﾟ"
                          },
                          "right": {
                            "type": "Literal",
                            "value": 3
                          }
                        },
                        "right": {
                          "type": "Literal",
                          "value": "_"
                        }
                      },
                      "property": {
                        "type": "BinaryExpression",
                        "operator": "-",
                        "left": {
                          "type": "Identifier",
                          "name": "ﾟｰﾟ"
                        },
                        "right": {
                          "type": "Identifier",
                          "name": "ﾟΘﾟ"
                        }
                      }
                    }
                  },
                  "right": {
                    "type": "MemberExpression",
                    "computed": true,
                    "object": {
                      "type": "Identifier",
                      "name": "ﾟДﾟ"
                    },
                    "property": {
                      "type": "Literal",
                      "value": "c"
                    }
                  }
                },
                "right": {
                  "type": "MemberExpression",
                  "computed": true,
                  "object": {
                    "type": "BinaryExpression",
                    "operator": "+",
                    "left": {
                      "type": "Identifier",
                      "name": "ﾟДﾟ"
                    },
                    "right": {
                      "type": "Literal",
                      "value": "_"
                    }
                  },
                  "property": {
                    "type": "BinaryExpression",
                    "operator": "+",
                    "left": {
                      "type": "Identifier",
                      "name": "ﾟｰﾟ"
                    },
                    "right": {
                      "type": "Identifier",
                      "name": "ﾟｰﾟ"
                    }
                  }
                }
              },
              "right": {
                "type": "MemberExpression",
                "computed": true,
                "object": {
                  "type": "Identifier",
                  "name": "ﾟДﾟ"
                },
                "property": {
                  "type": "Literal",
                  "value": "o"
                }
              }
            },
            "right": {
              "type": "MemberExpression",
              "computed": true,
              "object": {
                "type": "BinaryExpression",
                "operator": "+",
                "left": {
                  "type": "BinaryExpression",
                  "operator": "==",
                  "left": {
                    "type": "Identifier",
                    "name": "ﾟｰﾟ"
                  },
                  "right": {
                    "type": "Literal",
                    "value": 3
                  }
                },
                "right": {
                  "type": "Literal",
                  "value": "_"
                }
              },
              "property": {
                "type": "Identifier",
                "name": "ﾟΘﾟ"
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "Identifier",
              "name": "ﾟДﾟ"
            },
            "property": {
              "type": "Literal",
              "value": "_"
            }
          },
          "right": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "MemberExpression",
              "computed": true,
              "object": {
                "type": "BinaryExpression",
                "operator": "^",
                "left": {
                  "type": "BinaryExpression",
                  "operator": "^",
                  "left": {
                    "type": "Identifier",
                    "name": "o"
                  },
                  "right": {
                    "type": "Identifier",
                    "name": "_"
                  }
                },
                "right": {
                  "type": "Identifier",
                  "name": "o"
                }
              },
              "property": {
                "type": "Identifier",
                "name": "ﾟoﾟ"
              }
            },
            "property": {
              "type": "Identifier",
              "name": "ﾟoﾟ"
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "Identifier",
            "name": "ﾟεﾟ"
          },
          "right": {
            "type": "BinaryExpression",
            "operator": "+",
            "left": {
              "type": "BinaryExpression",
              "operator": "+",
              "left": {
                "type": "BinaryExpression",
                "operator": "+",
                "left": {
                  "type": "BinaryExpression",
                  "operator": "+",
                  "left": {
                    "type": "BinaryExpression",
                    "operator": "+",
                    "left": {
                      "type": "MemberExpression",
                      "computed": true,
                      "object": {
                        "type": "BinaryExpression",
                        "operator": "+",
                        "left": {
                          "type": "BinaryExpression",
                          "operator": "==",
                          "left": {
                            "type": "Identifier",
                            "name": "ﾟｰﾟ"
                          },
                          "right": {
                            "type": "Literal",
                            "value": 3
                          }
                        },
                        "right": {
                          "type": "Literal",
                          "value": "_"
                        }
                      },
                      "property": {
                        "type": "Identifier",
                        "name": "ﾟΘﾟ"
                      }
                    },
                    "right": {
                      "type": "MemberExpression",
                      "computed": false,
                      "object": {
                        "type": "Identifier",
                        "name": "ﾟДﾟ"
                      },
                      "property": {
                        "type": "Identifier",
                        "name": "ﾟДﾟﾉ"
                      }
                    }
                  },
                  "right": {
                    "type": "MemberExpression",
                    "computed": true,
                    "object": {
                      "type": "BinaryExpression",
                      "operator": "+",
                      "left": {
                        "type": "Identifier",
                        "name": "ﾟДﾟ"
                      },
                      "right": {
                        "type": "Literal",
                        "value": "_"
                      }
                    },
                    "property": {
                      "type": "BinaryExpression",
                      "operator": "+",
                      "left": {
                        "type": "Identifier",
                        "name": "ﾟｰﾟ"
                      },
                      "right": {
                        "type": "Identifier",
                        "name": "ﾟｰﾟ"
                      }
                    }
                  }
                },
                "right": {
                  "type": "MemberExpression",
                  "computed": true,
                  "object": {
                    "type": "BinaryExpression",
                    "operator": "+",
                    "left": {
                      "type": "BinaryExpression",
                      "operator": "==",
                      "left": {
                        "type": "Identifier",
                        "name": "ﾟｰﾟ"
                      },
                      "right": {
                        "type": "Literal",
                        "value": 3
                      }
                    },
                    "right": {
                      "type": "Literal",
                      "value": "_"
                    }
                  },
                  "property": {
                    "type": "BinaryExpression",
                    "operator": "^",
                    "left": {
                      "type": "BinaryExpression",
                      "operator": "^",
                      "left": {
                        "type": "Identifier",
                        "name": "o"
                      },
                      "right": {
                        "type": "Identifier",
                        "name": "_"
                      }
                    },
                    "right": {
                      "type": "BinaryExpression",
                      "operator": "-",
                      "left": {
                        "type": "Identifier",
                        "name": "o"
                      },
                      "right": {
                        "type": "Identifier",
                        "name": "ﾟΘﾟ"
                      }
                    }
                  }
                }
              },
              "right": {
                "type": "MemberExpression",
                "computed": true,
                "object": {
                  "type": "BinaryExpression",
                  "operator": "+",
                  "left": {
                    "type": "BinaryExpression",
                    "operator": "==",
                    "left": {
                      "type": "Identifier",
                      "name": "ﾟｰﾟ"
                    },
                    "right": {
                      "type": "Literal",
                      "value": 3
                    }
                  },
                  "right": {
                    "type": "Literal",
                    "value": "_"
                  }
                },
                "property": {
                  "type": "Identifier",
                  "name": "ﾟΘﾟ"
                }
              }
            },
            "right": {
              "type": "MemberExpression",
              "computed": true,
              "object": {
                "type": "BinaryExpression",
                "operator": "+",
                "left": {
                  "type": "Identifier",
                  "name": "ﾟωﾟﾉ"
                },
                "right": {
                  "type": "Literal",
                  "value": "_"
                }
              },
              "property": {
                "type": "Identifier",
                "name": "ﾟΘﾟ"
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "+=",
          "left": {
            "type": "Identifier",
            "name": "ﾟｰﾟ"
          },
          "right": {
            "type": "Identifier",
            "name": "ﾟΘﾟ"
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "Identifier",
              "name": "ﾟДﾟ"
            },
            "property": {
              "type": "Identifier",
              "name": "ﾟεﾟ"
            }
          },
          "right": {
            "type": "Literal",
            "value": "\\"
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "MemberExpression",
            "computed": false,
            "object": {
              "type": "Identifier",
              "name": "ﾟДﾟ"
            },
            "property": {
              "type": "Identifier",
              "name": "ﾟΘﾟﾉ"
            }
          },
          "right": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "BinaryExpression",
              "operator": "+",
              "left": {
                "type": "Identifier",
                "name": "ﾟДﾟ"
              },
              "right": {
                "type": "Identifier",
                "name": "ﾟｰﾟ"
              }
            },
            "property": {
              "type": "BinaryExpression",
              "operator": "^",
              "left": {
                "type": "BinaryExpression",
                "operator": "^",
                "left": {
                  "type": "Identifier",
                  "name": "o"
                },
                "right": {
                  "type": "Identifier",
                  "name": "_"
                }
              },
              "right": {
                "type": "BinaryExpression",
                "operator": "-",
                "left": {
                  "type": "Identifier",
                  "name": "o"
                },
                "right": {
                  "type": "Identifier",
                  "name": "ﾟΘﾟ"
                }
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "Identifier",
            "name": "oﾟｰﾟo"
          },
          "right": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "BinaryExpression",
              "operator": "+",
              "left": {
                "type": "Identifier",
                "name": "ﾟωﾟﾉ"
              },
              "right": {
                "type": "Literal",
                "value": "_"
              }
            },
            "property": {
              "type": "BinaryExpression",
              "operator": "^",
              "left": {
                "type": "BinaryExpression",
                "operator": "^",
                "left": {
                  "type": "Identifier",
                  "name": "c"
                },
                "right": {
                  "type": "Identifier",
                  "name": "_"
                }
              },
              "right": {
                "type": "Identifier",
                "name": "o"
              }
            }
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "AssignmentExpression",
          "operator": "=",
          "left": {
            "type": "MemberExpression",
            "computed": true,
            "object": {
              "type": "Identifier",
              "name": "ﾟДﾟ"
            },
            "property": {
              "type": "Identifier",
              "name": "ﾟoﾟ"
            }
          },
          "right": {
            "type": "Literal",
            "value": "\""
          }
        }
      },
      {
        "type": "ExpressionStatement",
        "expression": {
          $sig: {
            name: "root",
            match: {
              "type": "CallExpression",
              "callee": {
                "type": "CallExpression",
                "callee": {
                  "type": "MemberExpression",
                  "computed": true,
                  "object": {
                    "type": "Identifier",
                    "name": "ﾟДﾟ"
                  },
                  "property": {
                    "type": "Literal",
                    "value": "_"
                  }
                },
                "arguments": [
                  {
                    "type": "CallExpression",
                    "callee": {
                      "type": "CallExpression",
                      "callee": {
                        "type": "MemberExpression",
                        "computed": true,
                        "object": {
                          "type": "Identifier",
                          "name": "ﾟДﾟ"
                        },
                        "property": {
                          "type": "Literal",
                          "value": "_"
                        }
                      },
                      "arguments": [{
                        $sig: {
                          name: "code"
                        }
                      }]
                    },
                    "arguments": [
                      {
                        "type": "Identifier",
                        "name": "ﾟΘﾟ"
                      }
                    ]
                  }
                ]
              },
              "arguments": [
                {
                  "type": "Literal",
                  "value": "_"
                }
              ]
            }
          }
        }
      }
    ]
  }
};
